name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t sunny01elementals/sanatan-dharamaya-backend .
      - name: Publish Image to docker hub
        run: docker push sunny01elementals/sanatan-dharamaya-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull sunny01elementals/backend-app:latest
      - name: Delete old container
        run: docker rm -f sanatan-dharamaya-backend-container
      - name: Run Docker Container
        run: docker run -d -p 4000:5000 --name sanatan-dharamaya-backend-container -e N3LJYI12vZcvmspS sunny01elementals/sanatan-dharamaya-backend
